[git_branch]
symbol = "ï˜ "
style = "bold purple"

[git_status]
conflicted = '[ï±](bold red) '
ahead = '[ï¢](bold green) '
behind = '[ï£](bold yellow) '
diverged = '[ï‘¿](bold red) '
up_to_date = '[ï˜](bold blue) '
untracked = '[ï™](bold cyan) '
stashed = '[ï´](bold magenta) '
modified = '[ï„](bold yellow) '
staged = '[ï§ \($count\)](bold green)'
renamed = '[ï¡](bold purple) '
deleted = '[ï¨](bold red) '

[directory]
style = "bold blue"
read_only = " ï ½"
truncation_length = 3
truncation_symbol = "â€¦/"

[hostname]
ssh_only = true
style = "bold red"
format = "[ğŸŒ SSH:$hostname](bold red on yellow) "

[username]
style_user = "bold yellow"
style_root = "bold red"
format = "[$user]($style) "

[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red)"
vicmd_symbol = "[V](bold blue)"

[time]
disabled = false
format = "[$time](bold cyan) "
time_format = "%H:%M:%S"